### ISSUE TITLE
2.9.8 release (deprecated)

### ISSUE THREAD

**Issue by pyby** [SRGSSR/playsrg-ios#121]
As this 2.9.8 version will be the latest 2.9.x release, this task list is what we can / need to deliver, before the upcoming [3.0.0](https://github.com/SRGSSR/playsrg-ios/milestone/7) new version. Here is the list of the issues we have found:

### Bugs
- [ ] [Send correct User Agent](https://github.com/SRGSSR/srganalytics-apple/issues/36) on first events for analytics.

### Improvements
- [x] Energy efficiency improvements from [Letterbox](https://github.com/SRGSSR/srgletterbox-apple/issues/199) and SRG libraries.
- [x] [Airplay button visibility](https://github.com/SRGSSR/srgletterbox-apple/issues/201) fix.

### Compatibility for future versions

- [ ] Send the iOS version to the middleware in a query parameter.

**Comment by pyby** [comment]
This version will probably never be released.
3.0.0 version is for all supported iOS versions.

We have to keep those tiny tasks in the todo list.

**Comment by defagos** [comment]
The next version will be 3.0.0.

**Comment by defagos** [comment]
(The two remaining sub-tasks associated with this issue will be part of 3.0.0)
